### PR TITLE
avoiding possibility of deadlock and other changes

### PR DESCRIPTION
**Pull request by harold-toledo**
I know this is a very big pull request. The driving force for it was a deadlock I was hitting when doing some debugging in my app. Then I decided to do some other changes that I think to some extent avoid some complexity and bring more clarity.

The possibility of deadlock can occur when trying to remove ACKs, more precisely when invoking the removeAck(string guid) method on the StanConnection class. Steps and reasoning that can lead to it:

1 - Lets consider we are only going to publish a single message.
2 - When publishing, an instance of PublishAck is created and inserted in the pubAckMap BlockingDictionary. Also, a timer is scheduled to execute a callback if we don't receive an ACK from the server. The timer documentation explicitly says that callbacks can occur even after calling Dispose() on the timer. Excerpt from the System.Threading.Timer documentation:

> When a timer is no longer needed, use the Dispose method to free the resources held by the timer. Note that callbacks can occur after the Dispose() method overload has been called, because the timer queues callbacks for execution by thread pool threads.

3 - The ACK processing and the timer callback invocation happen in separate thread of executions.
4 - Now, lets consider that we receive the ACK, we call the removeAck method and the corresponding instance is removed from the pubAckMap BlockingDictionary, right about that time the timer fires and the callback is invoked. Now when we call the removeAck method, we acquire the lock on mu and try to remove the same ack instance from the pubAckMap BlockingDictionary, and this second attempt to remove the item from the blocking dictionary is the one that blocks and also holds the lock indefinitely.

If this pull request is to hard to review, I can split it and submit one part at a time.

### CODE REVIEW

**Comment by ColinSullivan1** [comment]
@harold-toledo , Thanks!  Good find with the timer callback and the dispose.  I do think it would be easier to review in pieces and would really appreciate it if you could split this up into PRs based on functionality / clarifying changes.  In the meantime, I'll take a look to get a sense of the changes involved.  Thanks!

**Comment by harold-toledo** [comment]
Hi, I know it has been a while but I have been very very busy at work and it will continue to be like that for some time. Would it be possible for you to review the pull request as it is right now? We have been using those changes in production since I created the PR and we have not had any problems so far.

**Comment by watfordgnf** [comment]
I think the hard part here to review is the change in style obscures the changes in function. I've pulled this down locally to review the files side-by-side and attempt to recreate this PR without any of the stylistic changes.

**Comment by watfordgnf** [comment]
I opened #100 to help review your PR without the stylistic changes.

**Comment by harold-toledo** [comment]
Regarding the test suite:

[Fact]
public void TestUnsubscribe()
       // Calling unsubscribe multiple times should not cause an exception to be thrown.
       Assert.Throws<StanBadSubscriptionException>(() => s.Unsubscribe());

[Fact]
public void TestNatsConn()					
       // When connection is closed this property is no longer set to null.
       // So this check no longer holds.
       Assert.True(c.NATSConnection == null);

**Pull request closed without merging**
